//! tsuki-ex firmware — main entry point
//!
//! The tsuki transpiler generates a `sketch.cpp` that implements:
//!   void tsuki_user_setup();
//!   void tsuki_user_loop();
//!
//! This Rust runtime calls them in order, wrapping them in module init,
//! power management, and watchdog handling.

#![no_std]
#![no_main]

use esp_idf_sys as _; // pulls in esp-idf bindings + panic handler

/// Generated by build.rs from TSUKI_FLAGS / TSUKI_MODULES env vars.
pub mod flags {
    include!(concat!(env!("OUT_DIR"), "/flags.rs"));
}

pub mod ffi;
pub mod hal;
pub mod modules;

use log::info;

/// Called once on boot — inits all active modules.
fn runtime_init() -> Result<(), esp_idf_sys::EspError> {
    esp_idf_svc::log::EspLogger::initialize_default();

    info!(
        "tsuki-ex fw v{} | mode={} | upload_baud={}",
        env!("CARGO_PKG_VERSION"),
        flags::POWER_MODE,
        flags::UPLOAD_BAUD,
    );

    match flags::POWER_MODE {
        1 => hal::power::set_low_power(),
        2 => hal::power::set_ultra_low_power(),
        _ => {}
    }

    #[cfg(feature = "filesystem")]
    modules::fs::init()?;

    #[cfg(feature = "wifi")]
    modules::wifi::init()?;

    #[cfg(feature = "bluetooth")]
    modules::bt::init()?;

    Ok(())
}

/// Entry point called from the C shim (app_main).
#[no_mangle]
pub extern "C" fn tsuki_runtime_run() {
    if let Err(e) = runtime_init() {
        log::error!("tsuki-ex init error: {:?}", e);
    }

    unsafe {
        tsuki_user_setup();
        loop {
            tsuki_user_loop();
            esp_idf_sys::vTaskDelay(1);
        }
    }
}

extern "C" {
    fn tsuki_user_setup();
    fn tsuki_user_loop();
}

#[no_mangle]
pub extern "C" fn app_main() {
    tsuki_runtime_run();
}
