/// tsuki-ex firmware build script
///
/// Reads TSUKI_FLAGS and TSUKI_MODULES env vars injected by the tsuki CLI/transpiler
/// and generates `src/flags.rs` with const values + re-exports cargo features.
///
/// Env vars set by tsuki before compilation:
///   TSUKI_FLAGS   = "UPLOAD=20000,MODE=2,BAUD=115200"
///   TSUKI_MODULES = "Wifi,Bt,Fs"
///
/// In user tsuki source:
///   // #[flags("UPLOAD=20000", "MODE=2")]
///   // #[modules(Wifi, Bt, Fs)]

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Required by esp-idf-sys / embuild
    embuild::espidf::sysenv::output();

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // ── Parse TSUKI_FLAGS ─────────────────────────────────────────────────────
    let raw_flags = env::var("TSUKI_FLAGS").unwrap_or_default();
    let flags: HashMap<String, String> = raw_flags
        .split(',')
        .filter_map(|pair| {
            let mut parts = pair.trim().splitn(2, '=');
            let k = parts.next()?.trim().to_uppercase();
            let v = parts.next().unwrap_or("1").trim().to_string();
            if k.is_empty() { None } else { Some((k, v)) }
        })
        .collect();

    // ── Parse TSUKI_MODULES ───────────────────────────────────────────────────
    let raw_modules = env::var("TSUKI_MODULES").unwrap_or_default();
    let modules: Vec<String> = raw_modules
        .split(',')
        .map(|m| m.trim().to_lowercase())
        .filter(|m| !m.is_empty())
        .collect();

    // ── Activate cargo features for modules ───────────────────────────────────
    // These will be picked up by #[cfg(feature = "...")] in the source.
    for module in &modules {
        match module.as_str() {
            "wifi"       => println!("cargo:rustc-cfg=feature=\"wifi\""),
            "bt"
            | "bluetooth" => println!("cargo:rustc-cfg=feature=\"bluetooth\""),
            "ble"        => {
                println!("cargo:rustc-cfg=feature=\"bluetooth\"");
                println!("cargo:rustc-cfg=feature=\"ble\"");
            }
            "fs"
            | "filesystem" => println!("cargo:rustc-cfg=feature=\"filesystem\""),
            other => eprintln!("cargo:warning=Unknown tsuki module: {other}"),
        }
    }

    // ── Generate src/flags.rs ─────────────────────────────────────────────────
    let mut out = String::from("// AUTO-GENERATED by build.rs — do not edit\n\n");

    // Upload baud
    let upload = flags
        .get("UPLOAD")
        .and_then(|v| v.parse::<u32>().ok())
        .unwrap_or(2_000_000);
    out.push_str(&format!("pub const UPLOAD_BAUD: u32 = {upload};\n"));

    // Serial monitor baud
    let baud = flags
        .get("BAUD")
        .and_then(|v| v.parse::<u32>().ok())
        .unwrap_or(115_200);
    out.push_str(&format!("pub const MONITOR_BAUD: u32 = {baud};\n"));

    // MODE (0 = normal, 1 = low-power, 2 = ultra-low-power)
    let mode = flags
        .get("MODE")
        .and_then(|v| v.parse::<u8>().ok())
        .unwrap_or(0);
    out.push_str(&format!("pub const POWER_MODE: u8 = {mode};\n"));

    // All remaining flags as string constants
    out.push_str("\n// User-defined flags\n");
    for (k, v) in &flags {
        if matches!(k.as_str(), "UPLOAD" | "BAUD" | "MODE") {
            continue;
        }
        // Only emit numeric constants; skip anything that can't parse
        if let Ok(n) = v.parse::<i64>() {
            let safe_key = k.replace('-', "_");
            out.push_str(&format!("pub const FLAG_{safe_key}: i64 = {n};\n"));
        }
    }

    // Active modules as bool consts
    out.push_str("\n// Active modules\n");
    for name in &["wifi", "bluetooth", "ble", "filesystem"] {
        let active = modules.iter().any(|m| {
            m == name
                || (name == &"bluetooth" && m == "bt")
                || (name == &"filesystem" && m == "fs")
        });
        out.push_str(&format!(
            "pub const MODULE_{}: bool = {active};\n",
            name.to_uppercase()
        ));
    }

    fs::write(out_dir.join("flags.rs"), out).expect("Failed to write flags.rs");

    // Tell cargo to re-run if these env vars change
    println!("cargo:rerun-if-env-changed=TSUKI_FLAGS");
    println!("cargo:rerun-if-env-changed=TSUKI_MODULES");
    println!("cargo:rerun-if-changed=build.rs");
}
